version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: jjcsa
      POSTGRES_USER: admin
      POSTGRES_DB: jjcsa
  backend:
    image: jjcsa:1.0
    ports:
      - "9080:9080"
    environment:
      - "SPRING_PROFILES_ACTIVE=local,docker"
    depends_on:
      - db