# Specify port to start the app in
server:
  port: 9080
  error:
    include-message: always # shows error message when ResponseStatusException is thrown

# Database config
spring:
  application:
    name: jjcsa-backend
#  config:
#    import: "aws-parameterstore:"
  jpa:
    database: POSTGRESQL
  datasource:
    username: admin
    password: jjcsa

cors:
  allowed-origin-patterns: '*'

security:
  enabled: true

# Keycloak Config
keycloak:
  realm: jjcsa-services
  bearer-only: true
  ssl-required: none
  resource: jjcsa
  cors: true
  use-resource-role-mappings: true

# AWS properties
aws:
  s3:
    bucketname: jjcsa-usa
  region: us-east-1
#  paramstore:
#    enabled: true
#    region: us-east-2

cloud:
  aws:
    ses:
      region:
        static: us-east-2
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
       useDefaultAwsCredentialsChain: true
#      profile-name: default
#      access-key:
#      secret-key:

email:
  ses:
    from-email: noreply@jjcsausa.com

frontend:
  forgotPasswordURL: localhost:5000/forgot-password-reset

show-community-proof : false

google:
  recaptcha:
    secret: 6LfA_E8lAAAAAOQNavNTak-bug4jPr-NuASqsgCp