spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://postgres-keycloak:5432/jjcsa
    username: admin
    password: jjcsa

security:
  enabled: false

keycloak:
  auth-server-url: http://keycloak:8080/auth

cloud:
  aws:
    credentials:
      profile-name: default