# Specify port to start the app in
server:
  port: 9080

# Database config
spring:
  jpa:
    database: POSTGRESQL
  datasource:
    username: admin
    password: jjcsa

cors:
  allowed-origin-patterns: '*'

security:
  enabled: true

# Keycloak Config
keycloak:
  realm: jjcsa-services
  bearer-only: true
  ssl-required: none
  resource: jjcsa
  cors: true
  use-resource-role-mappings: true

# AWS properties
aws:
  s3:
    bucketname: jjcsa-usa
  region: us-east-1

cloud:
  aws:
    ses:
      region:
        static: us-east-2
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
       useDefaultAwsCredentialsChain: true
#      profile-name: default
#      access-key:
#      secret-key:
