spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
  datasource:
    # Will be replaced by environment variables
    url: ${BACKEND_DB_URL}
    username: ${BACKEND_DB_UNAME}
    password: ${BACKEND_DB_PW}

keycloak:
  auth-server-url: ${KEYCLOACK_URL}