spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/jjcsa
    # Will be set by aws parameter store variables.
    # for username it should be /config/application_stage(for whole application with stage profile)/spring.datasource.username
    # Same for PW.

management:
  endpoints:
    web:
      cors:
        allowed-origin-patterns: 'http://*.jjcsausa.com'

keycloak:
  auth-server-url: http://backend.jjcsausa.com:8080/auth/