# Specify port to start the app in
server:
  port: 9080

# Database config
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
  datasource:
    platform: postgres
    username: jjcsa
    password: jjcsa-jjcsa

# Keycloak Config
keycloak:
  realm: jjcsa-services
  bearer-only: true
  ssl-required: none
  resource: jjcsa
  cors: true
  use-resource-role-mappings: true

# AWS properties
aws:
  s3:
    bucketname: jjcsa-usa
  region: us-east-1

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
#      profile-name: default
#      access-key:
#      secret-key: